x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: 10M
      max-file: 3

services:
  judge0:
    image: judge0/judge0:1.13.1
    ports:
      - "2358:2358"
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    environment:
      - RAILS_MAX_THREADS=1
      - RAILS_SERVER_PROCESSES=1
    cpus: 1.5
    mem_limit: 512m
    <<: *default-logging
    restart: unless-stopped
    depends_on:
      - db
      - redis

  db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: judge0
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: NjEZ8eMKQHkMujZwmUpmEdYYFuJBmQRE
    volumes:
      - db_data:/var/lib/postgresql/data
    cpus: 0.5
    mem_limit: 256m
    <<: *default-logging
    restart: unless-stopped

  redis:
    image: redis:7.2.4
    command: >
      redis-server
      --appendonly no
      --requirepass uy89UJC2DnzQDPYF8Cuj7f2xJyCUtQM5
    cpus: 0.25
    mem_limit: 128m
    <<: *default-logging
    restart: unless-stopped

volumes:
  db_data:
